Repository sendgrid/open-source-library-data-collector, pull requests merged in 2018-10, with the labels that each got.

#125 Fix cyclomatic complexity issues
  github.py
  sendgrid_email.py
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#127 Remove duplicate Build Status Travis Badge
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#128 Update LICENSE.txt to 2018 for Travis CI unit test
  LICENSE.txt
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#130 Create dummy files to fix tests
  .travis.yml
  USE_CASES.md
  docker/Dockerfile
  docker/docker-compose.yml
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#131 Fix SendGrid and GitHub typos
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#118 Add Code Review to Contributing.md #117
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#157 PEP-8 Fixes and String Formatting Enhancement
  TROUBLESHOOTING.md
  config.py
  db_connector.py
  setup.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement
